
CREATE TABLE IF NOT EXISTS adresse (
    idadresse INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    rue VARCHAR (255) NOT NULL,
    complement VARCHAR (255),
    ville VARCHAR (100) NOT NULL,
    code_postal VARCHAR (10) NOT NULL,
    pays VARCHAR(100) NOT NULL,
    datecreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    datemodification TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);